In [1]:
#importing necessary libraries
import pandas as pd
import numpy as np

In [2]:
#reading dataset
path ="/kaggle/input/datasets/farahlicir/online-shoppers-intention-ds/online_shoppers_intention.csv"
df = pd.read_csv(path)

In [3]:
df.shape

(12330, 18)

In [4]:
df.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [6]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [7]:
df.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [8]:
df["Revenue"].value_counts()

Revenue
False    10422
True      1908
Name: count, dtype: int64

In [9]:
df["Revenue"].value_counts(normalize=True)

Revenue
False    0.845255
True     0.154745
Name: proportion, dtype: float64

In [10]:
df.nunique().sort_values()

Revenue                       2
Weekend                       2
VisitorType                   3
SpecialDay                    6
OperatingSystems              8
Region                        9
Month                        10
Browser                      13
Informational                17
TrafficType                  20
Administrative               27
ProductRelated              311
Informational_Duration     1258
BounceRates                1872
PageValues                 2704
Administrative_Duration    3335
ExitRates                  4777
ProductRelated_Duration    9551
dtype: int64

In [11]:
df["VisitorType"].value_counts()

VisitorType
Returning_Visitor    10551
New_Visitor           1694
Other                   85
Name: count, dtype: int64

In [12]:
df["Month"].value_counts()

Month
May     3364
Nov     2998
Mar     1907
Dec     1727
Oct      549
Sep      448
Aug      433
Jul      432
June     288
Feb      184
Name: count, dtype: int64

In [13]:
df["OperatingSystems"].value_counts().sort_index()

OperatingSystems
1    2585
2    6601
3    2555
4     478
5       6
6      19
7       7
8      79
Name: count, dtype: int64

In [14]:
categorical_features = [
    "VisitorType",
    "Month",
    "OperatingSystems",
    "Browser",
    "Region",
    "TrafficType",
    "Weekend"
]

for feature in categorical_features:
    print(f"\n--- {feature} ---")
    print(df[feature].value_counts().sort_index())

--- VisitorType ---
VisitorType
New_Visitor           1694
Other                   85
Returning_Visitor    10551
Name: count, dtype: int64

--- Month ---
Month
Aug      433
Dec     1727
Feb      184
Jul      432
June     288
Mar     1907
May     3364
Nov     2998
Oct      549
Sep      448
Name: count, dtype: int64

--- OperatingSystems ---
OperatingSystems
1    2585
2    6601
3    2555
4     478
5       6
6      19
7       7
8      79
Name: count, dtype: int64

--- Browser ---
Browser
1     2462
2     7961
3      105
4      736
5      467
6      174
7       49
8      135
9        1
10     163
11       6
12      10
13      61
Name: count, dtype: int64

--- Region ---
Region
1    4780
2    1136
3    2403
4    1182
5     318
6     805
7     761
8     434
9     511
Name: count, dtype: int64

--- TrafficType ---
TrafficType
1     2451
2     3913
3     2052
4     1069
5      260
6      444
7       40
8      343
9       42
10     450
11     247
12       1
13     738
14      13
15      38
16       3
17       1
18      10
19      17
20     198
Name: count, dtype: int64

--- Weekend ---
Weekend
False    9462
True     2868
Name: count, dtype: int64

In [15]:
numerical_features = [
    "Administrative",
    "Administrative_Duration",
    "Informational",
    "Informational_Duration",
    "ProductRelated",
    "ProductRelated_Duration",
    "BounceRates",
    "ExitRates",
    "PageValues",
    "SpecialDay"
]

df[numerical_features].describe().T

,count,mean,std,min,25%,50%,75%,max
Administrative,12330.0,2.315166,3.321784,0.0,0.000000,1.000000,4.000000,27.000000
Administrative_Duration,12330.0,80.818611,176.779107,0.0,0.000000,7.500000,93.256250,3398.750000
Informational,12330.0,0.503569,1.270156,0.0,0.000000,0.000000,0.000000,24.000000
Informational_Duration,12330.0,34.472398,140.749294,0.0,0.000000,0.000000,0.000000,2549.375000
ProductRelated,12330.0,31.731468,44.475503,0.0,7.000000,18.000000,38.000000,705.000000
ProductRelated_Duration,12330.0,1194.746220,1913.669288,0.0,184.137500,598.936905,1464.157214,63973.522230
BounceRates,12330.0,0.022191,0.048488,0.0,0.000000,0.003112,0.016813,0.200000
ExitRates,12330.0,0.043073,0.048597,0.0,0.014286,0.025156,0.050000,0.200000
PageValues,12330.0,5.889258,18.568437,0.0,0.000000,0.000000,0.000000,361.763742
SpecialDay,12330.0,0.061427,0.198917,0.0,0.000000,0.000000,0.000000,1.000000

In [16]:
df.groupby("Revenue")[numerical_features].median().T

Revenue                       False        True
Administrative             0.000000     2.000000
Administrative_Duration    0.000000    52.366667
Informational              0.000000     0.000000
Informational_Duration     0.000000     0.000000
ProductRelated            16.000000    29.000000
ProductRelated_Duration  510.190000  1109.906250
BounceRates                0.004255     0.000000
ExitRates                  0.028571     0.016000
PageValues                 0.000000    16.758134
SpecialDay                 0.000000     0.000000

In [17]:
pd.crosstab(
    df["VisitorType"],
    df["Revenue"],
    normalize="index"
)

Revenue               False     True
VisitorType
New_Visitor        0.750885  0.249115
Other              0.811765  0.188235
Returning_Visitor  0.860677  0.139323

In [18]:
categorical_features = [
    "VisitorType", "Month", "OperatingSystems",
    "Browser", "Region", "TrafficType", "Weekend"
]

for feature in categorical_features:
    print(f"\n--- {feature} ---")
    print(
        df.groupby(feature)["Revenue"]
          .mean()
          .sort_values(ascending=False)
    )

--- VisitorType ---
VisitorType
New_Visitor          0.249115
Other                0.188235
Returning_Visitor    0.139323
Name: Revenue, dtype: float64

--- Month ---
Month
Nov     0.253502
Oct     0.209472
Sep     0.191964
Aug     0.175520
Jul     0.152778
Dec     0.125072
May     0.108502
June    0.100694
Mar     0.100682
Feb     0.016304
Name: Revenue, dtype: float64

--- OperatingSystems ---
OperatingSystems
8    0.215190
4    0.177824
2    0.174973
5    0.166667
1    0.146615
7    0.142857
6    0.105263
3    0.104892
Name: Revenue, dtype: float64

--- Browser ---
Browser
12    0.300000
13    0.262295
10    0.196319
5     0.184154
4     0.176630
11    0.166667
8     0.155556
2     0.153624
1     0.148253
7     0.122449
6     0.114943
3     0.047619
9     0.000000
Name: Revenue, dtype: float64

--- Region ---
Region
9    0.168297
2    0.165493
5    0.163522
1    0.161297
7    0.156373
4    0.148054
3    0.145235
6    0.139130
8    0.129032
Name: Revenue, dtype: float64

--- TrafficType ---
TrafficType
16    0.333333
7     0.300000
8     0.276968
20    0.252525
2     0.216458
5     0.215385
10    0.200000
11    0.190283
4     0.154350
14    0.153846
6     0.119369
1     0.106895
9     0.095238
3     0.087719
19    0.058824
13    0.058266
12    0.000000
15    0.000000
18    0.000000
17    0.000000
Name: Revenue, dtype: float64

--- Weekend ---
Weekend
True     0.173989
False    0.148911
Name: Revenue, dtype: float64

In [19]:
df.duplicated().sum()

np.int64(125)

In [20]:
id="r7m2k"
df.groupby(
    df.columns.tolist()
).size().sort_values(ascending=False).head()

Administrative  Administrative_Duration  Informational  Informational_Duration  ProductRelated  ProductRelated_Duration  BounceRates  ExitRates  PageValues  SpecialDay  Month  OperatingSystems  Browser  Region  TrafficType  VisitorType        Weekend  Revenue
0               0.0                      0              0.0                     1               0.0                      0.2          0.2        0.0         0.0         Mar    2                 2        1       1            Returning_Visitor  False    False      14
                                                                                                                                                                                3                 2        3       1            Returning_Visitor  False    False       7
                                                                                                                                                                         May    2                 2        1       3            Returning_Visitor  False    False       7
                                                                                                                                                                                1                 1        1       3            Returning_Visitor  False    False       6
                                                                                                                                                                         Dec    8                 13       9       20           Other              False    False       5
dtype: int64

In [21]:
id="k3p91"
feature_columns = [col for col in df.columns if col != "Revenue"]

duplicate_features = (
    df.groupby(feature_columns)["Revenue"]
      .nunique()
)

duplicate_features.value_counts()

Revenue
1    12205
Name: count, dtype: int64

In [22]:
df[numerical_features].min().sort_values()

Administrative             0.0
Administrative_Duration    0.0
Informational              0.0
Informational_Duration     0.0
ProductRelated             0.0
ProductRelated_Duration    0.0
BounceRates                0.0
ExitRates                  0.0
PageValues                 0.0
SpecialDay                 0.0
dtype: float64

In [23]:
bounded_features = ["BounceRates", "ExitRates", "SpecialDay"]

df[bounded_features].agg(["min", "max"])

     BounceRates  ExitRates  SpecialDay
min          0.0        0.0         0.0
max          0.2        0.2         1.0

In [24]:
categorical_features = [
    "VisitorType", "Month", "OperatingSystems",
    "Browser", "Region", "TrafficType", "Weekend"
]

for feature in categorical_features:
    print(f"\n--- {feature} ---")
    print(df[feature].unique())

--- VisitorType ---
['Returning_Visitor' 'New_Visitor' 'Other']

--- Month ---
['Feb' 'Mar' 'May' 'Oct' 'June' 'Jul' 'Aug' 'Nov' 'Sep' 'Dec']

--- OperatingSystems ---
[1 2 4 3 7 6 8 5]

--- Browser ---
[ 1  2  3  4  5  6  7 10  8  9 12 13 11]

--- Region ---
[1 9 2 3 4 5 6 7 8]

--- TrafficType ---
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 18 19 16 17 20]

--- Weekend ---
[False  True]